### ISSUE TITLE
Failed to fetch StrategyManager address

### ISSUE THREAD

**Issue by enzifiri** [Layr-Labs/eigenlayer-cli#37]
Hello, I get the following error after running ```eigenlayer operator register operator.yaml``` command. I use the Goerli Network and got the Rpc through Alchemy. I think there is a problem with the SDK 
https://github.com/Layr-Labs/eigensdk-go/tree/master/contracts/bindings/StrategyManager

```
2024-01-21T11:42:55.806Z        ERROR   logging/zap_logger.go:57        Failed to fetch StrategyManager address {"err": "no contract code at given address"}
github.com/Layr-Labs/eigensdk-go/logging.(*ZapLogger).Error
        /root/go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.0.9/logging/zap_logger.go:57
github.com/Layr-Labs/eigensdk-go/chainio/utils.NewEigenlayerContractBindings
        /root/go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.0.9/chainio/utils/bindings.go:49
github.com/Layr-Labs/eigensdk-go/chainio/clients/elcontracts.BuildELChainWriter
        /root/go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.0.9/chainio/clients/elcontracts/writer.go:98
github.com/Layr-Labs/eigenlayer-cli/pkg.OperatorCmd.RegisterCmd.func1
        /root/eigenlayer-cli/pkg/operator/register.go:114
github.com/urfave/cli/v2.(*Command).Run
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279
github.com/urfave/cli/v2.(*Command).Run
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272
github.com/urfave/cli/v2.(*Command).Run
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272
github.com/urfave/cli/v2.(*App).RunContext
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337
github.com/urfave/cli/v2.(*App).Run
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main
        /root/eigenlayer-cli/cmd/eigenlayer/main.go:34
runtime.main
        /usr/local/go/src/runtime/proc.go:267
no contract code at given address
```

# Operator.yaml;
```
operator:
    address: 0x6542de144ec034ac17712da8a1cc93c13899fd4b
    earnings_receiver_address: 0x6542de144ec034ac17712da8a1cc93c13899fd4b
    delegation_approver_address: "0x0000000000000000000000000000000000000000"
    staker_opt_out_window_blocks: 0
    metadata_url: "https://raw.githubusercontent.com/enzifiri/eigenlayer-cli/master/metadata.json"
el_slasher_address: ""
bls_public_key_compendium_address: ""
eth_rpc_url: https://eth-goerli.g.alchemy.com/v2/Jq1oomMShB5EaFoDz80Ay8xAN2WiAUiV
private_key_store_path: /root/.eigenlayer/operator_keys/wallet.ecdsa.key.json
signer_type: local_keystore
bls_private_key_store_path: /root/.eigenlayer/operator_keys/wallet.bls.key.json
chain_id: 5
```

Ubuntu 20.04 LTS
go version go1.21.6 linux/amd64
