### ISSUE TITLE
 "no contract code at given address" When Checking EigenLayer Node Status

### ISSUE THREAD

**Issue by ImanSharaf** [Layr-Labs/eigenlayer-cli#52]
When attempting to check the status of my EigenLayer node using the eigenlayer operator status operator-config.yaml command, I encounter the following error message:

2024/02/10 07:10:54 no contract code at given address

Also, git pull shows that the code is up to date! Do you have any idea why I get this error?
```

# All the below fields are required for successful operator registration.

operator:
  # This is the standard Ethereum address format (ex: 0x6a8c0D554a694899041E52a91B4EC3Ff23d8aBD5) of your operator
  # which is the ecdsa key you created or imported using EigenLayer CLI
  address: myaddress (redacted)
  # This is the standard Ethereum address format (ex: 0x6a8c0D554a694899041E52a91B4EC3Ff23d8aBD5)
  # This is the address where your operator will receive earnings. This could be same as operator address
  earnings_receiver_address: myaddress (redacted)
  # This is the standard Ethereum address format (0x...)
  # This is the address which operator will use to approve delegation requests from stakers.
  # if set, this address must sign and approve new delegation from Stakers to this Operator
  # This is optional, so you can leave it  with the default value for un-gated delegation requests
  delegation_approver_address: 0x0000000000000000000000000000000000000000
  # Please keep this field to 0, and it can be updated later using EigenLayer CLI
  staker_opt_out_window_blocks: 0
  metadata_url: https://raw.githubusercontent.com/ImanSharaf/Eigen/main/metadata.json

# EigenLayer Slasher contract address
# This will be provided by EigenLayer team
el_slasher_address: 0xD11d60b669Ecf7bE10329726043B3ac07B380C22
el_delegation_manager_address: 0x1b7b8F6b258f95Cf9596EabB9aa18B62940Eb0a8


# Address of BLS Public Key Compendium contract
# This will be provided by EigenLayer team
bls_public_key_compendium_address: 0xc81d3963087Fe09316cd1E032457989C7aC91b19

# ETH RPC URL to the ethereum node you are using for on-chain operations
eth_rpc_url: redacted (it is working okay)
# Signer Type to use
# Supported values: local_keystore
signer_type: local_keystore

# Full path to local ecdsa private key store file
private_key_store_path: /root/.eigenlayer/operator_keys/iman.ecdsa.key.json

# Full path to local bls private key store file
bls_private_key_store_path: /root/.eigenlayer/operator_keys/iman.bls.key.json

# Chain ID: 1 for mainnet, 5 for Goerli, 31337 for local
chain_id: 5
```
