### ISSUE TITLE
Failed to fetch StrategyManager address {"err": "no contract code at given address"}

### ISSUE THREAD

**Issue by niklaus-eigen** [Layr-Labs/eigenlayer-cli#87]
I am configuring as described in the offiical document, and I've tried the Goerli, Sepolia, and Holesky networks on my Ubuntu 20x operating system. However, I can't seem to get rid of this error. Below is an example of my config. Can you please help? What could be the issue?

Chain ids:
Goerli: 5
Holesky: 17000

operator:
    address: REDACTAD
    earnings_receiver_address: REDACTAD
    delegation_approver_address: "0x0000000000000000000000000000000000000000"
    staker_opt_out_window_blocks: 0
    metadata_url: "https://raw.githubusercontent.com/niklaus-eigen/eigenlayer/main/metadata.json"
el_slasher_address: "0xD11d60b669Ecf7bE10329726043B3ac07B380C22
el_delegation_manager_address: 0xA44151489861Fe9e3055d95adC98FbD462B948e7"
eth_rpc_url: https://ethereum-holesky-rpc.publicnode.com
private_key_store_path: /root/.eigenlayer/operator_keys/{NAME-REDACTAD}.ecdsa.key.json
signer_type: local_keystore
bls_private_key_store_path: /root/.eigenlayer/operator_keys/{NAME-REDACTAD}.bls.key.json
chain_id: 17000

**Comment by shrimalmadhur** [comment]
Hello @niklaus-eigen - you can remove the `el_slasher_address` field and you only need `el_delegation_manager_address` . Also I see some weird double quotes in config in the address? can that be the issue? Also what version of eigenlayer-cli are you using?

**Comment by Shekelme** [comment]
@shrimalmadhur
`eigenlayer version 0.5.1`
Recently I was able to successfully register an operator in Goerli testnet (using my locally deployed Goerli ETH RPC node). Now when I'm trying to do so in mainnet, I'm getting this error:

```
admfc@lenovo21:~$ eigenlayer operator register operator.yaml
Operator configuration file read successfully 0x208C37102cCcd0fbcd4aBe01a672125E05C6C607 ✅
validating operator config: 0x208C37102cCcd0fbcd4aBe01a672125E05C6C607 ⏳
Operator configuration file validated successfully 0x208C37102cCcd0fbcd4aBe01a672125E05C6C607 ✅
? Enter password to decrypt the bls private key: ***************
? Enter password to decrypt the ecdsa private key: ***************
2024-04-16T09:05:30.598+0300    ERROR   logging/zap_logger.go:57        Failed to fetch StrategyManager address {"err": "no contract code at given address"}
github.com/Layr-Labs/eigensdk-go/logging.(*ZapLogger).Error
        /home/ethereum/go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.0.9/logging/zap_logger.go:57
github.com/Layr-Labs/eigensdk-go/chainio/utils.NewEigenlayerContractBindings
        /home/ethereum/go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.0.9/chainio/utils/bindings.go:49
github.com/Layr-Labs/eigensdk-go/chainio/clients/elcontracts.BuildELChainWriter
        /home/ethereum/go/pkg/mod/github.com/!layr-!labs/eigensdk-go@v0.0.9/chainio/clients/elcontracts/writer.go:98
github.com/Layr-Labs/eigenlayer-cli/pkg.OperatorCmd.RegisterCmd.func1
        /home/ethereum/go/pkg/mod/github.com/!layr-!labs/eigenlayer-cli@v0.5.1/pkg/operator/register.go:114
github.com/urfave/cli/v2.(*Command).Run
        /home/ethereum/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279
github.com/urfave/cli/v2.(*Command).Run
        /home/ethereum/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272
github.com/urfave/cli/v2.(*Command).Run
        /home/ethereum/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272
github.com/urfave/cli/v2.(*App).RunContext
        /home/ethereum/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337
github.com/urfave/cli/v2.(*App).Run
        /home/ethereum/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main
        /home/ethereum/go/pkg/mod/github.com/!layr-!labs/eigenlayer-cli@v0.5.1/cmd/eigenlayer/main.go:34
runtime.main
        /snap/go/10489/src/runtime/proc.go:267
no contract code at given address
```
My mainnet ETh RPC node seems to be available:
```
admfc@lenovo21:~$ curl -I http://localhost:8545
HTTP/1.1 200 OK
Date: Tue, 16 Apr 2024 05:15:56 GMT
Server: Kestrel

admfc@lenovo21:~$ curl --location 'localhost:8545/' \
--header 'Content-Type: application/json' \
--data '{
        "jsonrpc":"2.0",
        "method":"web3_clientVersion",
        "params":[],
        "id":1
}'
{"jsonrpc":"2.0","result":"Nethermind/v1.25.4\u002B20b10b35/linux-x64/dotnet8.0.2","id":1}
```
operator.yaml looks like this:
```
operator:
    address: 0x208C37102cC3d0fbcd4aBe01a672125E05C6C607
    earnings_receiver_address: 0x208C37102cC3d0fbcd4aBe01a672125E05C6C607
    delegation_approver_address: "0x0000000000000000000000000000000000000000"
    staker_opt_out_window_blocks: 0
    metadata_url: https://raw.githubusercontent.com/Shekelme/EigenLayerRegistration/main/metadata.json
el_delegation_manager_address: 0x39053D51B77DC0d36036Fc1fCc8Cb819df8Ef37A
eth_rpc_url: http://127.0.0.1:8545
private_key_store_path: /home/admfc/.eigenlayer/operator_keys/saturnia.ecdsa.key.json
signer_type: local_keystore
bls_private_key_store_path: /home/admfc/.eigenlayer/operator_keys/saturnia.bls.key.json
chain_id: 1
```
